"""Writes src/families/irodori-tts/unicode-data.inc: the tables NFKC and str.strip() need, from the Unicode
version of this Python, which is the one the official runtime normalizes text with.

usage: uv run python gen_unicode.py ../../src/families/irodori-tts/unicode-data.inc

  kDecompositions   code point, offset and length into kDecompositionPool of its full compatibility
                    decomposition, for every code point that has one other than the Hangul syllables
  kCombiningClasses ranges of code points with the same non-zero canonical combining class
  kCompositions     the pairs that canonical composition joins, and what they join into, other than Hangul
  kWhitespace       ranges of the code points str.isspace() accepts
"""

import sys
import unicodedata

HANGUL_FIRST, HANGUL_LAST = 0xAC00, 0xD7A3


def ranges(values):
    """(first, last, value) runs of consecutive code points with the same value."""
    out = []
    for cp, value in values:
        if out and out[-1][1] == cp - 1 and out[-1][2] == value:
            out[-1][1] = cp
        else:
            out.append([cp, cp, value])
    return out


decompositions, pool = [], []
for cp in range(0x110000):
    if HANGUL_FIRST <= cp <= HANGUL_LAST:
        continue
    d = unicodedata.normalize("NFKD", chr(cp))
    if d != chr(cp):
        decompositions.append((cp, len(pool), len(d)))
        pool.extend(ord(c) for c in d)

combining = ranges((cp, unicodedata.combining(chr(cp))) for cp in range(0x110000) if unicodedata.combining(chr(cp)))

compositions = []
for cp in range(0x110000):
    if HANGUL_FIRST <= cp <= HANGUL_LAST:
        continue
    parts = unicodedata.decomposition(chr(cp)).split()
    if len(parts) != 2 or parts[0].startswith("<"):
        continue
    a, b = (int(p, 16) for p in parts)
    # Exclusions and non-starter decompositions are the pairs that NFC does not join back.
    if unicodedata.normalize("NFC", chr(a) + chr(b)) == chr(cp):
        compositions.append((a, b, cp))
compositions.sort()

whitespace = ranges((cp, 1) for cp in range(0x110000) if chr(cp).isspace())


def rows(items, per_line, fmt):
    lines = []
    for i in range(0, len(items), per_line):
        lines.append("    " + " ".join(fmt(x) + "," for x in items[i : i + per_line]))
    return "\n".join(lines)


with open(sys.argv[1], "w") as f:
    f.write(f"// Generated by reference/irodori-tts/gen_unicode.py from Unicode {unicodedata.unidata_version}.\n")
    f.write("static const Decomposition kDecompositions[] = {\n")
    f.write(rows(decompositions, 4, lambda d: "{0x%X, %d, %d}" % d) + "\n};\n")
    f.write("static const uint32_t kDecompositionPool[] = {\n")
    f.write(rows(pool, 10, lambda c: "0x%X" % c) + "\n};\n")
    f.write("static const CombiningClassRange kCombiningClasses[] = {\n")
    f.write(rows(combining, 4, lambda r: "{0x%X, 0x%X, %d}" % tuple(r)) + "\n};\n")
    f.write("static const Composition kCompositions[] = {\n")
    f.write(rows(compositions, 4, lambda c: "{0x%X, 0x%X, 0x%X}" % c) + "\n};\n")
    f.write("static const CodepointRange kWhitespace[] = {\n")
    f.write(rows(whitespace, 4, lambda r: "{0x%X, 0x%X}" % tuple(r[:2])) + "\n};\n")
print(unicodedata.unidata_version, len(decompositions), len(pool), len(combining), len(compositions), len(whitespace))
