"""Writes src/common/unicode-ranges.inc: the code point ranges of letters (L), numbers (N) and whitespace that
the Qwen2 pre-tokenizer's \\p{L}, \\p{N} and \\s match.

usage: uv run python gen_unicode.py ../../src/common/unicode-ranges.inc
"""

import sys
import unicodedata


def ranges(pred):
    out, start = [], None
    for cp in range(0x110000):
        if pred(chr(cp)):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def emit(name, rs):
    body = ",\n".join("    {0x%X, 0x%X}" % r for r in rs)
    return f"static const CodepointRange {name}[] = {{\n{body}\n}};\n"


letters = ranges(lambda c: unicodedata.category(c).startswith("L"))
numbers = ranges(lambda c: unicodedata.category(c).startswith("N"))
spaces = ranges(lambda c: c.isspace())
with open(sys.argv[1], "w") as f:
    f.write(f"// Generated by reference/qwen3-tts/gen_unicode.py from Unicode {unicodedata.unidata_version}.\n")
    f.write(emit("kLetters", letters))
    f.write(emit("kNumbers", numbers))
    f.write(emit("kSpaces", spaces))
print(len(letters), len(numbers), len(spaces))
